
<div class="content-top">
<h5 class="ContentHeadTitle">收货地址</h5>
<hr>
<!--<h5 style="color: #e97203">-->
<!--    新增收货人地址-->
<!--</h5>-->




<button class="btn btn-link" data-toggle="modal" data-target="#deliverAddressModal">
         添加收货地址
</button>
</div>
<style>
    .content-top{
        border: 1px solid #ddd;
        margin-bottom: 20px;
    }
    .content-top>hr{
        border-width: 2px 0 0;
        border-color:red;
        margin-bottom: 0px;
        margin-top: 12px;
    }
    .ContentHeadTitle{
        font-size: 20px;
        margin-top: 12px;
        margin-left: 12px;
        font-weight:bolder;
    }
</style>
<div>
    <table id="deliveryAddressTable" class="table table-bordered">
        <thead>
        <tr>
            <th>收货人姓名</th>
            <th>所在区域</th>
            <th>所在地址</th>
            <th>手机号码</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>


<div class="modal fade" id="deliverAddressModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">添加收货地址</h4>
            </div>
            <div class="modal-body">
                <form id="addDeliveryAddress" class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="inputReceiverName" class="col-sm-3 control-label">收货人姓名</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="inputReceiverName" name="inputReceiverName" placeholder="收货人姓名">
                        </div>
                    </div>

                    <div class="form-group form-inline">
                        <label for="Domain" class="col-sm-3 control-label">所在区域</label>

                        <div class="col-sm-8">
                            <select id="Domain" name="Domain" class="form-control">
                            </select>

                            <div id="Domain2Block" style="display: inline;">
                                -
                                <select class="form-control" id="Domain2" name="Domain2"></select>
                            </div>

                            <div id="Domain3Block" style="display: inline;">
                                -
                                <select class="form-control" id="Domain3" name="Domain3"></select>
                            </div>
                        </div>
                    </div>


                    <div class="form-group">
                        <label for="inputStreetAddress" class="col-sm-3 control-label">所在地址</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="inputStreetAddress" name="inputStreetAddress"
                                   placeholder="所在地址">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPhone" class="col-sm-3 control-label">手机号码</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="inputPhone" name="inputPhone" placeholder="手机号码">
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="button" class="btn btn-primary" onclick="$('#addDeliveryAddress').submit()">保存</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->