<div name="left-panel">

    <div class="col-xs-6 col-md-2">
        <a href="#" class="thumbnail">
            <img data-src="holder.js/100%x180" alt="..." src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNzEiIGhlaWdodD0iMTgwIj48cmVjdCB3aWR0aD0iMTcxIiBoZWlnaHQ9IjE4MCIgZmlsbD0iI2VlZSIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9Ijg1LjUiIHk9IjkwIiBzdHlsZT0iZmlsbDojYWFhO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjEycHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MTcxeDE4MDwvdGV4dD48L3N2Zz4=">
        </a>
        <div class="list-group">
            <?php if($menu) foreach($menu as $key=>$item): ?>

                <a href="#" id="<?php echo $key ?>" class="list-group-item <?php echo $key=='userinfo'?'active':'';?>">
                    <?php echo $item; ?>
                </a>
            <?php endforeach;?>
        </div>
    </div>
</div>
