
<div class="content-top">
    <h5 class="ContentHeadTitle">修改密码</h5>
    <hr>
</div>

<style>
    .content-top{
        border: 1px solid #ddd;
        margin-bottom: 20px;
    }
    .content-top>hr{
        border-width: 2px 0 0;
        border-color:red;
        margin-bottom: 0px;
        margin-top: 12px;
    }
    .ContentHeadTitle{
        font-size: 20px;
        margin-top: 12px;
        margin-left: 12px;
        font-weight:bolder;

    }
</style>
    <form id="passwordForm" class="form-horizontal" >
        <?php
        if($this->hasPwd):
        ?>
        <div class="form-group">
            <label for="oripwd" class="col-sm-1 control-label">原密码</label>
            <div class="col-sm-3">
                <input type="password" class="form-control" id="oripwd" name="oripwd" placeholder="原密码">
            </div>
        </div>
        <?php endif; ?>
        <div class="form-group">
            <label for="newpwd" class="col-sm-1 control-label">新密码</label>
            <div class="col-sm-3">
                <input type="password" class="form-control" id="newpwd" name="newpwd" placeholder="新密码">
            </div>
        </div>
        <div class="form-group">
            <label for="confirmPwd" class="col-sm-1 control-label">确认</label>
            <div class="col-sm-3">
                <input type="password" class="form-control" id="confirmPwd" name="confirmPwd" placeholder="确认">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-1 col-sm-10">
                <button  id="submitUserInfo" onclick="" class="btn btn-default">保存</button>
            </div>
        </div>
    </form>
