<div class="content-top">
    <h5 class="ContentHeadTitle">订单管理</h5>
    <hr>
</div>


<div>
        <div id="order1" class="tab-pane active in">
            <table id="userOrderMGRtable" class="table">
                <thead>
                <tr>
                    <th>订单号</th>
                    <th>总金额</th>
                    <th>下单时间</th>
                    <th>期待收货时间</th>
                    <th>收货人</th>
                    <th>联系电话</th>
                    <th>状态</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            <ul class="pager">
                <li><a id="preLink" href="#">上一页</a></li>
                <li><span>第<span id="currentPage">0</span>页/共<span id="totalPage">0</span>页</span></li>
                <li><a id="nextLink" href="#">下一页</a></li>
            </ul>
        </div>
</div>

<style>
    .content-top {
        border: 1px solid #ddd;
        margin-bottom: 20px;
    }

    .content-top > hr {
        border-width: 2px 0 0;
        border-color: red;
        margin-bottom: 0;
        margin-top: 12px;
    }

    .ContentHeadTitle {
        font-size: 20px;
        margin-top: 12px;
        margin-left: 12px;
        font-weight: bolder;
    }


    .userorder-tab > li > a {
        border-radius: 0 0 0 0;
    }
</style>