<?php
use Application\Model\OrderState;
use Application\Model\OrderStateMsg;

?>

<div class="content-top">
    <h5 class="ContentHeadTitle">订单管理</h5>
    <hr>
</div>


<div>
        <div id="order1" class="tab-pane active in">
            <table id="userOrderMGRtable" class="table">
                <thead>
                <tr>
                    <th style="width: 250px">订单信息</th>
                    <th style="text-align: right;">总金额</th>
                    <th>下单时间</th>
                    <th>期待收货时间</th>
                    <th>收货人</th>
                    <th>联系电话</th>
                    <th>状态</th>
                </tr>
                </thead>
                <?php


                if($this->list)
                foreach($this->list['order']['data'] as $row):
                ?>
                <tbody>
                    <tr>
                        <td colspan="7">订单号：<a href='/user/orderManage/detail/<?php echo $row['ID'] ?>'><?php echo $row['ID'] ?></a></td>
                    </tr>
                    <tr>
                        <td>
                            <?php
                            if(isset($this->list['detail'][$row['ID']]))
                            foreach($this->list['detail'][$row['ID']] as $detail): ?>
                            <img id="<?php echo $detail['ID'];?>" style="padding: 1px;width: 50px;height: 50px;" title="<?php echo $detail['Name']; ?>" src="http://<?php echo imgServer ?>/goodsimg/tiny/<?php echo $detail['Image'];?>">
                            <?php endforeach;?>
                        </td>
                        <td style="text-align: right"><?php echo number_format($row['Total'],2) ?></td>
                        <td><?php echo $row['OrderTime'] ?></td>
                        <td><?php echo $row['ExpectTime'] ?></td>
                        <td><?php echo $row['Name'] ?></td>
                        <td><?php echo $row['Phone'] ?></td>
                        <td><?php
                            /*
                            1:Wait Confirm
                            2:Confirm and Appoint Worker
                            3:Reject and Set Comment
                            9:End Mission
                            */

                            switch($row["State"]){
                                case OrderState::WAITING_CONFIRM:
                                    echo OrderStateMsg::WAITING_CONFIRM;
                                    break;
                                case OrderState::CONFIRM_AND_APPOINT_TO_WORKER:
                                    echo OrderStateMsg::CONFIRM_AND_APPOINT_TO_WORKER;
                                    break;
                                case OrderState::REJECT_AND_SET_COMMENT:
                                    echo OrderStateMsg::REJECT_AND_SET_COMMENT;
                                    break;
                                case OrderState::END_MISSION:
                                    echo OrderStateMsg::END_MISSION;
                                    break;
                                default:
                                    echo OrderStateMsg::OTHER;
                            }
                            ?></td>
                    </tr>
                </tbody>

                <?php endforeach;?>
            </table>
            <ul class="pager">
                <li><a id="preLink" href="#">上一页</a></li>
                <li><span>第<span id="currentPage"><?php echo $this->list['order']['page']; ?></span>页/共<span id="totalPage"><?php echo $this->list['order']['total']; ?></span>页</span></li>
                <li><a id="nextLink" href="#">下一页</a></li>
            </ul>
        </div>
</div>

<style>
    .content-top {
        border: 1px solid #ddd;
        margin-bottom: 20px;
    }

    .content-top > hr {
        border-width: 2px 0 0;
        border-color: red;
        margin-bottom: 0;
        margin-top: 12px;
    }

    .ContentHeadTitle {
        font-size: 20px;
        margin-top: 12px;
        margin-left: 12px;
        font-weight: bolder;
    }


    .userorder-tab > li > a {
        border-radius: 0 0 0 0;
    }
</style>

<script>

    $().ready(function(){
        var page = $('#currentPage').html();
        var total = $('#totalPage').html();

        if(page=="1"){
            $('.pager li:first-child').html('<span >上一页</span>')


        }else{
            $('.pager li:first-child').html('<a id="preLink" href="?page=' + (parseInt(page)-1) +
                '" >上一页</a>');

        }

        if(page==total){
            $('.pager li:last-child').html('<span>下一页</span>')
        }else{
            $('.pager li:last-child').html('<a id="nextLink" href="?page=' +(parseInt(page)+1) +
                '" >下一页</a>');

        }
    });

</script>