


<div class="col-md-2" id="container-menu">
    <?php echo $menu; ?>
</div>


<div class="col-md-10" id="container-content">
    <div class="row-fluid">
        <button class="btn btn-default span2" data-toggle="modal" data-target="#addWorker" onclick="flushFormValues()">添加员工</button>

        <select class="form-control span2" id="state-select" onchange="changeState()">
            <option value="0">全部</option>
            <option value="1">正常</option>
            <option value="8">解约</option>
            <option value="9">禁用</option>
        </select>

        <div class="input-group span3">
            <input type="text" class="form-control span9" id="searchText">
             <span class="input-group-btn">
             <button class="btn btn-default" type="button" onclick="searchTextChange()">查找</button>
             </span>
        </div><!-- /input-group -->
        <div class="span1 pull-right" id="loading" style="display: none;">
            <img src="<?php echo $this->basePath()?>/images/loading.gif" style="width: 34px;"/>
        </div>
        <button class="btn btn-default span2" onclick="getSelectedIdArray()" style="display: block">TEST</button>
    </div>
    <!--    <input type="search" class="form-control"/>-->
    <div style="padding-top: 5px;">
        <table class="table table-bordered table-hover">
            <thead style="background-color:#428bca;color: white;">
            <tr>
                <td style="width: 30px"><input id="check-all" type="checkbox" onclick="checkAllBoxes()"/></td>
                <td>工号</td>
                <td>姓名</td>
                <td>性别</td>
                <td>证件号</td>
                <!--                <td>联系电话</td>-->
                <td>联系电话</td>
                <td>状态</td>
                <td>操作</td>
            </tr>
            </thead>
            <tbody style="background-color: white" id="workerTable">
            <?php foreach ($workerTable as $worker): ?>
            <tr id="tr-<?php echo $worker->getID()?>">
                <td><input id="check-<?php echo $worker->getID();?>" type="checkbox"/></td>
                <td><?php echo $worker->getUsername(); ?></td>
                <td><?php echo $worker->getName(); ?></td>
                <td><?php echo $worker->getSex(); ?></td>
                <td><?php echo $worker->getCertNumber(); ?></td>
                <td><?php echo $worker->getPhone(); ?></td>
                <td>
                    <?php
                    $state = $worker->getState();
                    switch($state){
                        case 1:echo "正常";break;
                        case 8:echo "解约";break;
                        case 9:echo "禁用";break;
                        default: echo "未知";break;
                    }
                    ?>
                </td>
                <td>
                    <a href="#" onclick="viewWorker(<?php echo $worker->getID(); ?>)">查看</a>
                    <a href="#" onclick="editWorkerOpen(<?php echo $worker->getID(); ?>)">编辑</a>
                </td>
            </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <!--        分页-->
        <ul class="pager">
            <li><a href="#" onclick="prevPage()">上一页</a></li>
            <li class="disabled"><span>第<span id="curPage">1</span>页/共<span id="allPages"><?php echo ceil($count/10)?></span>页</span></li>
            <li><a href="#" onclick="nextPage()">下一页</a></li>
        </ul>

    </div>
</div>

<!--    添加员工-->
<div class="modal fade" id="addWorker" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 450px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title">添加员工</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="reg-username" class="col-sm-3 control-label">工号</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="reg-username" placeholder="6-16个字母、数字">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="reg-password" class="col-sm-3 control-label">密码</label>
                        <div class="col-sm-8">
                            <input type="password" class="form-control" id="reg-password" placeholder="6-16个字符">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="reg-repassword" class="col-sm-3 control-label">重复密码</label>
                        <div class="col-sm-8">
                            <input type="password" class="form-control" id="reg-repassword" placeholder="请重复输入密码">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="reg-name" class="col-sm-3 control-label">姓名</label>
                        <div class="col-sm-8">
                            <input type="email" class="form-control" id="reg-name" placeholder="请输入真实姓名">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="reg-sex1" class="col-sm-3 control-label">性别</label>
                        <div class="col-sm-8">
<!--                            <input type="email" class="form-control" id="reg-sex" placeholder="请输入Email地址">-->
                            <label class="radio-inline">
                                <input type="radio" name="reg-sex" value="男" checked="true"> 男
                            </label>
                            <label class="radio-inline">
                                <input type="radio" name="reg-sex" value="女"> 女
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="reg-certNumber" class="col-sm-3 control-label">证件号</label>
                        <div class="col-sm-8">
                            <input type="email" class="form-control" id="reg-certNumber" placeholder="请输入证件号">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="reg-phone" class="col-sm-3 control-label">联系电话</label>
                        <div class="col-sm-8">
                            <input type="email" class="form-control" id="reg-phone" placeholder="请输入联系电话">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="reg-selfPhone" class="col-sm-3 control-label">个人电话</label>
                        <div class="col-sm-8">
                            <input type="email" class="form-control" id="reg-selfPhone" placeholder="选填">
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <div style="float:left;margin-left: 80px; width: 200px;"><div id="reg-message" style="color: red;"></div></div>
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" onclick="addWorker()">确定</button>
            </div>
        </div>
    </div>
</div>

<!--    编辑员工-->
<div class="modal fade" id="editWorker" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 450px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title">编辑员工</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form">
                    <input type="text" class="form-control" id="edit-id" style="display: none"/>
                    <div class="form-group">
                        <label for="edit-username" class="col-sm-3 control-label">工号</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="edit-username" disabled="true">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit-password" class="col-sm-3 control-label">密码</label>
                        <div class="col-sm-8">
                            <input type="password" class="form-control" id="edit-password" placeholder="**********">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit-repassword" class="col-sm-3 control-label">重复密码</label>
                        <div class="col-sm-8">
                            <input type="password" class="form-control" id="edit-repassword" placeholder="**********">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit-name" class="col-sm-3 control-label">姓名</label>
                        <div class="col-sm-8">
                            <input type="email" class="form-control" id="edit-name">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit-sex1" class="col-sm-3 control-label">性别</label>
                        <div class="col-sm-8">
                            <!--                            <input type="email" class="form-control" id="reg-sex" placeholder="请输入Email地址">-->
                            <label class="radio-inline">
                                <input type="radio" name="edit-sex" value="男" checked="true"> 男
                            </label>
                            <label class="radio-inline">
                                <input type="radio" name="edit-sex" value="女"> 女
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit-certNumber" class="col-sm-3 control-label">证件号</label>
                        <div class="col-sm-8">
                            <input type="email" class="form-control" id="edit-certNumber">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit-phone" class="col-sm-3 control-label">联系电话</label>
                        <div class="col-sm-8">
                            <input type="email" class="form-control" id="edit-phone">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit-selfPhone" class="col-sm-3 control-label">个人电话</label>
                        <div class="col-sm-8">
                            <input type="email" class="form-control" id="edit-selfPhone" placeholder="选填">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit-state" class="col-sm-3 control-label">状态</label>
                        <div class="col-sm-8">
                            <select class="form-control" id="edit-state">
                                <option value="1">正常</option>
                                <option value="8">解约</option>
                                <option value="9">禁用</option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <div style="float:left;margin-left: 80px; width: 200px;"><div id="edit-message" style="color: red;"></div></div>
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" onclick="editWorker()">确定</button>
            </div>
        </div>
    </div>
</div>

<!--    查看员工-->
<div class="modal fade" id="viewWorker" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 450px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title">查看员工</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="view-username" class="col-sm-4 control-label">工号</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="view-username"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="view-name" class="col-sm-4 control-label">姓名</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="view-name"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="view-sex" class="col-sm-4 control-label">性别</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="view-sex"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="view-certNumber" class="col-sm-4 control-label">证件号</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="view-certNumber"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="view-phone" class="col-sm-4 control-label">联系电话</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="view-phone"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="view-selfPhone" class="col-sm-4 control-label">个人电话</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="view-selfPhone"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="view-loginTime" class="col-sm-4 control-label">最近登录时间</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="view-loginTime"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="view-loginIP" class="col-sm-4 control-label">最近登录IP</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="view-loginIP"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="view-state" class="col-sm-4 control-label">状态</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="view-state"></p>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
            </div>
        </div>
    </div>
</div>
