<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Worker\Module'                        => __DIR__ . '/Module.php',
    'Worker\Controller\WorkerController' => __DIR__ . '/src/Worker/Controller/WorkerController.php',
    'Worker\Controller\WorkerOrderController' => __DIR__ . '/src/Worker/Controller/WorkerOrderController.php',
    'WorkerTest\Framework\TestCase'        => __DIR__ . '/tests/Worker/Framework/TestCase.php',
    'WorkerTest\SampleTest'                => __DIR__ . '/tests/Worker/SampleTest.php',
);
