<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Authenticate\Module'                        => __DIR__ . '/Module.php',
    'Authenticate\Controller\AuthenticateController' => __DIR__ . '/src/Authenticate/Controller/AuthenticateController.php',
    'AuthenticateTest\Framework\TestCase'        => __DIR__ . '/tests/Authenticate/Framework/TestCase.php',
    'AuthenticateTest\SampleTest'                => __DIR__ . '/tests/Authenticate/SampleTest.php',
    'QC' =>getcwd().'/API/QQAPI/qqConnectAPI.php',
);
