<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('快递鼠')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.gif'))
        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
        ->prependStylesheet($this->basePath() . '/css/topMenu.css')
        ->prependStylesheet($this->basePath() . '/css/home.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
    ?>

    <!-- Scripts -->
    <?php
    echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() .'/js/jquery.validate.min.js')
        ->prependFile($this->basePath() .'/js/paramsCheck.js')
        ->prependFile($this->basePath() .'/js/md5.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js');
    ?>
<style>
    .login-header{
        margin: 0 auto;
        padding: 0;
        width: 1100px;
    }
    .login-container{
        margin: 0 auto;
        padding: 0;
        width: 990px;
        height: 768px;
    }
    .login-footer{
        margin: 0 auto;
        padding: 0;
        width: 990px;
        text-align: center;
    }
    #logo{
        float: none;
        margin: 0;
        padding: 10px 0;
        position: relative;
    }
    #logo b{
        background: url("/images/login-all-bg.png") no-repeat scroll 0 0 rgba(0, 0, 0, 0);
        height: 44px;
        left: 180px;
        position: absolute;
        top: 44px;
        width: 152px;
        padding: 10px 0;
        margin-left: 30px;
    }
</style>
</head>
<body style="height: 768px">
<div class="login-header">
    <div id="logo">
        <a href="/">
            <img width="181" height="98" alt="快递鼠" src="/images/logo.jpg">
        </a>
        <b></b>
    </div>
</div>
<div class="login-container">
    <?php echo $this->content; ?>
</div>
<!-- /container -->

<div class="login-footer">
    <div>
        <a href="###">公司简介</a> |
        <a href="###">加入我们</a> |
        <a href="###">常见问题</a> |
        <a href="###">联系客服</a> |
        <a href="###">网站地图</a>
    </div>

    <div>Copyright &copy;2014-2015 快递鼠 版权所有 | 粤ICP备14052553号</div>
</div>
<?php echo $this->inlineScript() ?>
</body>
</html>
