<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AdminBase\Module'                        => __DIR__ . '/Module.php',
    'AdminBase\Controller\AdminBaseControllerController' => __DIR__ . '/src/AdminBase/Controller/AdminBaseController.php',
    'AdminBaseTest\Framework\TestCase'        => __DIR__ . '/tests/AdminBase/Framework/TestCase.php',
    'AdminBaseTest\SampleTest'                => __DIR__ . '/tests/AdminBase/SampleTest.php',
);
