

<div class="content-top">
    <h5 class="ContentHeadTitle">商品管理<div class="span1 pull-right" id="loading" style="display: none;">
            <img src="<?php echo $this->basePath()?>/images/loading.gif" style="width: 30px;"/>
        </div>
    </h5>

    <hr>
</div>

<div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <td>商品编号</td>
            <td>商品名称</td>
            <td>商品分类</td>
            <td>商品价格</td>
<!--            <td>单位</td>-->
            <td>状态</td>
            <td width="150px">操作</td>
        </tr>
        </thead>
        <tbody>
        <?php foreach($this->goodsList as $item):   ?>

        <tr>
            <td><?php echo $item->getID() ?></td>
            <td><?php echo $item->getName() ?></td>
            <td><?php echo $item->getMainClassName()."-".$item->getClassName() ?></td>
            <td><?php
                $standards = $item->getGoodsStandards();
                $priceArr = \Application\Model\CommonFunctions::getPricesFromStandards($standards);
                if($priceArr["min"] == $priceArr["max"]) echo $priceArr["min"];
                else echo $priceArr["min"]."-".$priceArr["max"];
                ?>元</td>
<!--            <td>--><?php //echo $item["Unit"] ?><!--</td>-->
            <td><?php switch($item->getState()){
                    case "1" : echo "在售"; break;
                    case "2" : echo "售罄"; break;
                }
                ?></td>
            <td>
                <a href="#" onclick="viewGoods(<?php echo $item->getID()?>)">查看</a>
                <a href="#" onclick="editGoodsOpen(<?php echo $item->getID()?>)">编辑</a>
                <a href="#" onclick="editStandardOpen(<?php echo $item->getID();?>)">修改价格</a>
            </td>

        </tr>

        <?php endforeach;?>
        </tbody>
    </table>
    <!--        分页-->
    <ul class="pager">
        <?php
            $lastPage = $pager["page"]-1<1? 1:$pager["page"]-1;
            $nextPage = $pager["page"]+1>ceil($pager["all"]/$pager["count"])? ceil($pager["all"]/$pager["count"]):$pager["page"]+1;
        ?>
        <li class="<?php if($pager["page"]-1<1) echo "disabled"?>">
            <a href="?page=<?php echo $lastPage?>" >上一页</a>
        </li>
        <li class="disabled"><span>第<?php echo $pager["page"]?>页/共<?php echo ceil($pager["all"]/$pager["count"])?>页</span></li>
        <li class="<?php if($pager["page"]+1>ceil($pager["all"]/$pager["count"])) echo "disabled"?>">
            <a href="?page=<?php echo $nextPage?>">下一页</a>
        </li>
    </ul>
</div>

<!--    查看商品-->
<div class="modal fade" id="viewGoods" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 450px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title">查看商品</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <img id="view-image" style="width: 200px; max-height: 150px;" class="center-block"/>
                    </div>
                    <div class="form-group">
                        <label for="view-seller" class="col-sm-4 control-label">商家名称</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="view-seller"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="view-mainClass" class="col-sm-4 control-label">主分类</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="view-mainClass"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="view-class" class="col-sm-4 control-label">子分类</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="view-class"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="view-name" class="col-sm-4 control-label">商品名称</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="view-name"></p>
                        </div>
                    </div>
<!--                    <div class="form-group">-->
<!--                        <label for="view-price" class="col-sm-4 control-label">价格</label>-->
<!--                        <div class="col-sm-7">-->
<!--                            <p class="form-control-static" id="view-price"></p>-->
<!--                        </div>-->
<!--                    </div>-->
                    <div class="form-group">
                        <label for="view-state" class="col-sm-4 control-label">状态</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="view-state"></p>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
            </div>
        </div>
    </div>
</div>

<!--    编辑商品-->
<div class="modal fade" id="editGoods" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 450px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title">编辑商品</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form">
                    <input type="text" class="form-control" id="edit-id" style="display: none"/>
                    <div class="form-group">
                        <label for="edit-seller" class="col-sm-3 control-label">商家</label>
                        <div class="col-sm-8">
                            <input id="edit-sellerId" style="display: none;"/>
                            <input id="edit-seller" class="form-control" readonly/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit-mainClassId" class="col-sm-3 control-label">主分类</label>
                        <div class="col-sm-8">
                            <select class="form-control" id="edit-mainClassId" onchange="changeMainClassInEdit()">
                                <?php foreach ($mainClassTable as $mainClass): ?>
                                    <option value="<?php echo $mainClass->getID()?>"><?php echo $mainClass->getName()?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit-classId" class="col-sm-3 control-label">分类</label>
                        <div class="col-sm-8">
                            <select class="form-control" id="edit-classId">

                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit-name" class="col-sm-3 control-label">商品名称</label>
                        <div class="col-sm-8">
                            <input type="email" class="form-control" id="edit-name"/>
                        </div>
                    </div>
                    <div class="form-group" id="edit-showImg">
                        <div class="col-sm-3"></div>
                        <div class="col-sm-8">
                            <img id="edit-img" style="width: 200px; max-height: 150px;"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit-image" class="col-sm-3 control-label">商家图片</label>
                        <div class="col-sm-8">
                            <input type="file" accept="image/*" class="form-control" id="edit-image"
                                   onchange="imageChanged(this, $('#edit-img'))">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit-price" class="col-sm-3 control-label">商品单位</label>
                        <div class="col-sm-8">
                            <input id="edit-unit" class="form-control" style="width: 100px;"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit-state" class="col-sm-3 control-label">状态</label>
                        <div class="col-sm-8">
                            <select id="edit-state" class="form-control">
                                <option value="1">在售</option>
                                <option value="2">售罄</option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <div style="float:left;margin-left: 80px; width: 200px;"><div id="edit-message" style="color: red;"></div></div>
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" onclick="editGoods()">确定</button>
            </div>
        </div>
    </div>
</div>

<!--    编辑商品规格 -->
<div class="modal fade" id="editStandard" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 450px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title">编辑商品规格</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form">
                    <input type="text" class="form-control" id="edit-standard-id" style="display: none"/>
                    <div class="form-group">
                        <label for="view-name" class="col-sm-4 control-label">商品名称</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="edit-standard-name"></p>
                        </div>
                    </div>
                    <hr/>
                    <div class="form-group">
                        <div class="col-sm-4" style="text-align: center;font-weight: bold;">
                            规格
                        </div>
                        <div class="col-sm-4" style="text-align: center;font-weight: bold;">
                            价格
                        </div>
                        <div class="col-sm-3" style="text-align: center;font-weight: bold;">
                            状态
                        </div>
                    </div>
                    <div class="form-group" id="standard-add">
                        <div class="col-sm-4">
                            <a href="###" onclick="addBlankStandard()">添加新规格</a>
                        </div>
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <div style="float:left;margin-left: 80px; width: 200px;"><div id="edit-standard-message" style="color: red;"></div></div>
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" onclick="editStandardSubmit()">确定</button>
            </div>
        </div>
    </div>
</div>


<style>
    .content-top{
        border: 1px solid #ddd;
        margin-bottom: 20px;
    }
    .content-top>hr{
        border-width: 2px 0 0;
        border-color:red;
        margin-bottom: 0;
        margin-top: 12px;
    }
    .ContentHeadTitle{
        font-size: 20px;
        margin-top: 12px;
        margin-left: 12px;
        font-weight:bolder;
    }
    .goods-modify-box{

    }
</style>

