<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Goods\Module'                        => __DIR__ . '/Module.php',
    'Goods\Controller\GoodsController' => __DIR__ . '/src/Goods/Controller/GoodsController.php',
    'GoodsTest\Framework\TestCase'        => __DIR__ . '/tests/Goods/Framework/TestCase.php',
    'GoodsTest\SampleTest'                => __DIR__ . '/tests/Goods/SampleTest.php',
);
