<?php foreach ($sellers as $seller): $flag = true;?>
    <div class="col-sm-3 col-lg-3 col-md-3 col-xs-3">
        <a href="<?php echo $this->basePath() ?>/home/seller/<?php echo $seller->getName() ?>"
           class="thumbnail home-thumbnail sellerThumbnail">
            <img src="<?php echo \Application\Model\StaticInfo::getSellerLogoAddress() ?><?php echo $seller->getLogo(); ?>"
                 style="height: 180px; width: 100%; display: block;">
        </a>

        <p class="seller-label"><?php echo $seller->getName(); ?></p>
    </div>
<?php endforeach; ?>