<div class="login-footer">
    <div>
        <a href="###">公司简介</a> |
        <a href="###">加入我们</a> |
        <a href="###">常见问题</a> |
        <a href="###">联系客服</a> |
        <a href="###">网站地图</a>
    </div>

    <div>Copyright &copy;2014-2015 快递鼠 版权所有 | 粤ICP备14052553号</div>
</div>

<style>

    .login-footer{
        margin: 0 auto;
        padding: 0;
        width: 990px;
        text-align: center;
    }

</style>