<div class="col-md-12 userinfo-localNav" style="line-height: 40px">
    <h4>我的快递鼠</h4>
<!--    <ol class="breadcrumb myBread">-->
<!--        --><?php
//        foreach($this->links as $href=>$name):
//        ?>
<!--        <li><a href="--><?php //echo $href;?><!--">--><?php //echo $name; ?><!--</a></li>-->
<!--        --><?php //endforeach;?>
<!--    </ol>-->

<!--    <a href="--><?php //echo $href;?><!--">--><?php //echo $name; ?><!--</a>-->

</div>

<style>
    .userinfo-localNav{

    }
    .userinfo-localNav a{
        color: #808080;
    }
    /*.userinfo-localNav a:hover,a:focus{*/
        /*color: #ff0000;*/
        /*text-decoration: underline;*/
    /*}*/
    .userinfo-localNav>h4{
        font-weight: bolder;

    }
    .myBread {
        background-color: rgba(255, 255, 255, 0);
        border-radius: 0;
        list-style: none outside none;
        margin-bottom: 0;
        padding: 0 0;
    }
</style>