<?php echo $this->doctype(); ?>

<html lang="zh">
<head>
    <?php echo $this->headTitle('ZF2 ' . $this->translate('Sticky Notes'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <meta charset="utf-8">

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.gif'))
        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
        ->prependStylesheet($this->basePath() . '/css/home.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
    ?>

    <!-- Scripts -->
    <?php
    echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))

        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/userInfo.js')
        ->appendFile($this->basePath() .'/js/jquery.validate.min.js')
        ->appendFile($this->basePath() .'/js/paramsCheck.js')
        ->appendFile($this->basePath() .'/js/md5.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')

    ?>

</head>
<body>
<?php if ($this->topNavbar) echo $this->topNavbar; ?>
<div id="locationBar" class="container">
    <div style="display: inline;font-weight: bold; line-height: 40px;" class="col-xs-6 col-md-2">我的快递鼠
        <div id="locationBread" style="display: inline;font-weight: lighter;">>收货地址</div>
    </div>
</div>
<div class="container">
    <?php echo $this->content; ?>

</div>
<!-- /container -->
<hr>
<footer class="text-center">
    <p>&copy; 2005 - 2012 by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>

    <p>Handcrafted with ♥ in Los Angeles by Big Employee LLC.user layout</p>
</footer>
<?php echo $this->inlineScript() ?>
</body>
</html>
