<script type="application/javascript" src="<?php echo $this->basePath()?>/js/jquery.cookie.js"></script>
<script type="application/javascript" src="<?php echo $this->basePath()?>/js/cart.js"></script>
<script type="application/javascript" src="<?php echo $this->basePath()?>/js/jquery.validate.min.js"></script>
<script type="application/javascript" src="<?php echo $this->basePath()?>/js/home/order.js"></script>
<script type="application/javascript" src="<?php echo $this->basePath()?>/js/user/addDeliveryAddressModal.js"></script>

<?php
$totalCnt = 0;
$totalMoney = 0;
?>

<div style="padding-top: 10px; padding-bottom: 20px;">
    <div style="display:inline; font-weight: bold; font-size: x-large">
        <span class="glyphicon glyphicon-list-alt"></span> 提交订单
    </div>
    <img src="<?php echo $this->basePath() ?>/images/提交订单2.png" class="pull-right"/>
</div>
<div>
    <div style="display: inline;font-size: large;font-weight: bold">订单内容</div>
    <div class="cart-divider"></div>
</div>
<table class="table">
    <thead>
    <tr>
        <th>商品</th>
        <th>单价</th>
        <th>数量</th>
        <th>小计</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($goods as $goodsGroup):
        $sellerName = reset($goodsGroup)["sellerName"];?>
        <tr>
            <td colspan="5" style="font-size: large; font-weight: bold;">
                <a href="<?php echo $this->basePath()."/home/seller/".$sellerName;?>" style="color: #E4393C;">
                    <?php echo $sellerName?></a>
            </td>
        </tr>
        <?php foreach($goodsGroup as $good):
        $totalCnt += intval($good["count"]);
        $totalMoney += floatval( floatval($good["price"]) * intval($good["count"]) );
        ?>
        <tr class="tr-item">
            <td>
                <img class="cart-image" src="<?php echo \Application\Model\StaticInfo::getGoodsTinyAddress().$good['image']?>"/>
                <?php echo $good["name"]?><?php echo $good["standard"]=="默认"?"":"(".$good["standard"].")"?>
            </td>
            <td class="price"><?php echo $good["price"]?></td>
            <td><?php echo $good["count"]?> </td>
            <td class="total"><?php echo sprintf("%.1f",floatval($good["price"])*intval($good["count"])) ?></td>
        </tr>
    <?php endforeach;?>
    <?php endforeach;?>

    </tbody>
</table>

<div style="height: 30px">
    <p class="cart-total">共 <strong class="count"><?php echo $totalCnt;?></strong> 件商品 &nbsp;&nbsp;&nbsp;
        金额：<strong class="total"><?php echo sprintf("%.1f",$totalMoney);?></strong> </p>
</div>


<?php if(count($warnings)>0):?>
<div>
    <div style="display: inline;font-size: large;font-weight: bold">温馨提示</div>
    <div class="cart-divider"></div>
</div>
<div style="margin-bottom: 20px;">
    <?php $warningStr = "";
        foreach($warnings as $warning):?>
        <h4><span class="glyphicon glyphicon-exclamation-sign"></span>
        <?php $warningStr .= $warning . '<br/>'; echo $warning; ?>
        </h4>
    <?php endforeach;?>
</div>
    <script>
        $().ready(function(){
            showMsgBeforeSubmitOrder('<?php echo $warningStr?>');
        });
    </script>
<?php endif;?>

<div>
    <div style="display: inline;font-size: large;font-weight: bold" id="fillAddress">填写收货地址</div>
    <div class="cart-divider"></div>
</div>

<table class="table" id="addressTable">
    <thead>
    <tr>
        <th style="width: 100px"></th>
        <th style="width: 20px"></th>
        <th style="width: 20%">收货人</th>
        <th>收货地址</th>
        <th style="width: 20%">联系电话</th>
        <th style="width: 5%"></th>
    </tr>
    </thead>
    <tbody id="addressTBody">
    <?php foreach($addresses as $address):?>
        <tr id="address-<?php echo $address["ID"]?>" onclick="sendToThisEffect($(this))">
            <td style="color: #ff0000">
                <div class="sendtothismarker" id="sendtothis-<?php echo $address["ID"]?>" style="display: none;">
                    <span style="color: #ff0000 !important" class="glyphicon glyphicon-map-marker"></span> 寄送至
                </div>
            </td>
            <td><input type="radio" name="addressRadio" value="<?php echo $address["ID"]?>"/></td>
            <td><?php echo $address["Name"]?></td>
            <td><?php echo $address["Domain"]." ".$address["Domain2"]." ".$address["Domain3"]." ".$address["Address"]?></td>
            <td><?php echo $address["Phone"]?></td>
            <td><a href="###" onclick="editAddressOpen(<?php echo $address["ID"]?>)">修改</a></td>
        </tr>
    <?php endforeach;?>
    <tr id="address-0" onclick="$(this).children().first().next().children().first()[0].checked=true" data-toggle="modal" data-target="#deliverAddressModal">
        <td></td>
        <td><input type="radio" name="addressRadio" value="0"/></td>
        <td>添加收货地址</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    </tbody>
</table>

<div>
    <div style="display: inline;font-size: large;font-weight: bold">填写备注</div>
    <div class="cart-divider"></div>
</div>
<div style="margin-top: 5px; margin-bottom: 10px">
    <textarea id="remarkText" class="form-control" style="resize: vertical" rows="2" placeholder="可选"></textarea>
</div>

<div style="padding-top: 10px;">
    <button class="btn btn-default" onclick="window.location.href='/home/cart'">返回购物车</button>
    <button class="btn btn-danger pull-right" data-loading-text="提交订单..." onclick="submitOrder($(this))" >提交订单
        <span style="color: #ffffff !important" class="glyphicon glyphicon-ok"></span></button>
    <div class="pull-right" style="margin-right: 20px; padding-top: 5px; font-size: medium;color: #ff0000" id="wrongMsg"></div>
</div>

<!--add address form  copy from delivery.phtml-->

<div class="modal fade" id="deliverAddressModal" tabindex="-1" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" onclick="closeAddrModal()"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">添加收货地址</h4>
            </div>
            <div class="modal-body">
                <form id="addDeliveryAddress" class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="inputReceiverName" class="col-sm-3 control-label">收货人姓名</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="inputReceiverName" name="inputReceiverName" placeholder="收货人姓名">
                        </div>
                    </div>

                    <div class="form-group form-inline">
                        <label for="Domain" class="col-sm-3 control-label">所在区域</label>

                        <div class="col-sm-8">
                            <select id="Domain" name="Domain" class="form-control DomainClass">
                            </select>

                            <div id="Domain2Block" style="display: inline;">
                                -
                                <select class="form-control Domain2Class" id="Domain2" name="Domain2"></select>
                            </div>

                            <div id="Domain3Block" style="display: inline;">
                                -
                                <select class="form-control Domain3Class" id="Domain3" name="Domain3"></select>
                            </div>
                        </div>
                    </div>


                    <div class="form-group">
                        <label for="inputStreetAddress" class="col-sm-3 control-label">所在地址</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="inputStreetAddress" name="inputStreetAddress"
                                   placeholder="填写宿舍号，如：238">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPhone" class="col-sm-3 control-label">手机号码</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="inputPhone" name="inputPhone" placeholder="请填写长号">
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" onclick="closeAddrModal()">关闭</button>
                <button type="button" class="btn btn-primary" onclick="$('#addDeliveryAddress').submit()">保存</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!--edit address-->
<div class="modal fade" id="editDeliverAddressModal" tabindex="-1" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">修改收货地址</h4>
            </div>
            <div class="modal-body">
                <form id="editDeliveryAddress" class="form-horizontal" role="form">
                    <input id="editAddressID" style="display: none;"/>

                    <div class="form-group">
                        <label for="editInputReceiverName" class="col-sm-3 control-label">收货人姓名</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="editInputReceiverName" placeholder="收货人姓名">
                        </div>
                    </div>

                    <div class="form-group form-inline">
                        <label for="Domain" class="col-sm-3 control-label">所在区域</label>

                        <div class="col-sm-8">
                            <select id="DomainEdit" name="Domain" class="form-control DomainClass" onchange="getEditDomain2List($(this).val(),function(){$('#Domain3Edit').children().remove();})">
                            </select>

                            <div id="Domain2Block" style="display: inline;">
                                -
                                <select class="form-control Domain2Class" id="Domain2Edit" name="Domain2" onchange="getEditDomain3List($(this).parent().prev().val(), $(this).val(), null)"></select>
                            </div>

                            <div id="Domain3Block" style="display: inline;">
                                -
                                <select class="form-control Domain3Class" id="Domain3Edit" name="Domain3"></select>
                            </div>
                        </div>
                    </div>


                    <div class="form-group">
                        <label for="editInputStreetAddress" class="col-sm-3 control-label">所在地址</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="editInputStreetAddress" placeholder="所在地址">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="editInputPhone" class="col-sm-3 control-label">手机号码</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="editInputPhone" placeholder="手机号码">
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="button" class="btn btn-primary" onclick="editAddress()">保存</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!--show message before submit order-->
<div class="modal fade" id="msgBeforeSubmit" tabindex="-1" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">重要信息</h4>
            </div>
            <div class="modal-body" id="msgBeforeSubmitContent" style="font-size: large;">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">知道了</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<script>

    function sendToThisEffect(obj){
        obj.children().first().next().children().first()[0].checked=true;
        $('.sendtothismarker').hide();
        obj.children().first().children().first().show();

        obj.parent().children().removeClass("sendtothis warning");
        obj.addClass("sendtothis warning");

    }

    $().ready(function(){
        $('#addressTBody').children().first().click();
//        if($('#addressTBody').children().length>1){
//            $('#addressTBody').children().first().click();
//        }else{
//            $('#addressTBody').children().first().click();
//        }

    });

    function closeAddrModal(){
        if($('#addressTBody').children().length <= 1){
            window.location.href = "/home/cart";
        }else{
            $('#deliverAddressModal').modal('hide');
            $('#addressTBody').children().first().click();
        }
    }

</script>

<style>
.sendtothis{
    font-size: large;
}
    .alertDiv{
        box-shadow: 0 0 10px red;
    }
</style>