<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Mobile\Module'                        => __DIR__ . '/Module.php',
    'Mobile\Controller\MobileController' => __DIR__ . '/src/Mobile/Controller/MobileController.php',
    'MobileTest\Framework\TestCase'        => __DIR__ . '/tests/Mobile/Framework/TestCase.php',
    'MobileTest\SampleTest'                => __DIR__ . '/tests/Mobile/SampleTest.php',
);
