<footer class="text-center">
    <p>
        <a href="/post/29" target="_blank">公司简介</a> |
        <a href="/post/33" target="_blank">加入我们</a> |
        <a href="/post/34" target="_blank">常见问题</a> |
        <a href="###" data-toggle="modal" data-target="#kefuModal">联系客服</a> |
        <a href="/post/39" target="_blank">招商加盟</a>
    </p>
    <p>Copyright &copy;2014-2015 快递鼠 版权所有 | 粤ICP备14052553号</p>
</footer>


<!-- Modal -->
<div class="modal fade" id="kefuModal" tabindex="-1" role="dialog" aria-labelledby="kefuModal" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">客服电话</h4>
            </div>
            <div class="modal-body" style="text-align: center;">
                <img src="/images/kflogo.jpg"/>
                <h4>客服QQ：1109221178</h4>
                <h4>客服电话：13826046484</h4>
<!--                <h4>广大短号：123456</h4>-->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
            </div>
        </div>
    </div>
</div>