<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AdminMgr\Module'                        => __DIR__ . '/Module.php',
    'AdminMgr\Controller\OrderController' => __DIR__ . '/src/AdminMgr/Controller/OrderController.php',
    'AdminMgr\Controller\PostController' => __DIR__ . '/src/AdminMgr/Controller/PostController.php',
    'AdminMgr\Controller\OrderAssignController' => __DIR__ . '/src/AdminMgr/Controller/OrderAssignController.php',
    'AdminMgrTest\Framework\TestCase'        => __DIR__ . '/tests/AdminMgr/Framework/TestCase.php',
    'AdminMgrTest\SampleTest'                => __DIR__ . '/tests/AdminMgr/SampleTest.php',
);
