<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Seller\Module'                        => __DIR__ . '/Module.php',
    'Seller\Controller\SellerController' => __DIR__ . '/src/Seller/Controller/SellerController.php',
    'Seller\Controller\SellerGoodsController' => __DIR__ . '/src/Seller/Controller/SellerGoodsController.php',
    'Seller\Controller\SellerOrderMgrController' => __DIR__ . '/src/Seller/Controller/SellerOrderMgrController.php',
    'SellerTest\Framework\TestCase'        => __DIR__ . '/tests/Seller/Framework/TestCase.php',
    'SellerTest\SampleTest'                => __DIR__ . '/tests/Seller/SampleTest.php',
);

