<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Administrator\Module'                        => __DIR__ . '/Module.php',
    'Administrator\Controller\AdministratorController' => __DIR__ . '/src/Administrator/Controller/AdministratorController.php',
    'AdministratorTest\Framework\TestCase'        => __DIR__ . '/tests/Administrator/Framework/TestCase.php',
    'AdministratorTest\SampleTest'                => __DIR__ . '/tests/Administrator/SampleTest.php',
);
