


<div class="container">
    <div class="col-sm-6 offset2">
        <h2 style="text-align: center">商品导入</h2>
        <br/>
        <form class="form-horizontal" role="form">
            <div class="form-group">
                <label for="import-sellerId" class="col-sm-3 control-label">商家</label>
                <div class="col-sm-8">
                    <select class="form-control" id="import-sellerId">
                        <?php foreach($sellers as $seller):?>
                        <option value="<?php echo $seller->getID()?>"><?php echo $seller->getName()?></option>
                        <?php endforeach;?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="import-dir" class="col-sm-3 control-label">商品目录</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="import-dir" value='C:\Users\Administrator\Desktop\牛状元'/>
<!--                    <input type="file" webkitdirectory directory multiple class="form-control" id="import-dir">-->
                </div>
            </div>
            <div class="form-group">
                <label for="import-xls" class="col-sm-3 control-label">商品表格xls</label>
                <div class="col-sm-8">
                    <input type="file" accept="application/vnd.ms-excel" class="form-control" id="import-xls">
                </div>
            </div>
        </form>

        <a href="http://static.kuaidishu.com/files/sample/产品录入Sample.xls" class="btn btn-info pull-right">下载模板</a>
        <button class="btn btn-default pull-right" onclick="importGoods()" style="margin-right: 20px">确定导入</button>
    </div>
</div>
