



<div class="col-md-2" id="container-menu">
    <?php echo $menu; ?>
</div>


<div class="col-md-10" id="container-content">
    <div class="row-fluid">
        <button class="btn btn-default span2" data-toggle="modal" data-target="#addGoods" onclick="flushFormValues()">添加商品</button>

        <select class="form-control span2" id="seller-select" onchange="changeSeller()">
            <option value="0">全部</option>
            <?php foreach ($sellerTable as $seller): ?>
                <option value="<?php echo $seller->getID()?>"><?php echo $seller->getName()?></option>
            <?php endforeach;?>
        </select>

        <select class="form-control span2" id="mainClass-select" onchange="changeMainClass()">
            <option value="0">全部</option>
            <?php foreach ($mainClassTable as $mainClass): ?>
            <option value="<?php echo $mainClass->getID()?>"><?php echo $mainClass->getName()?></option>
            <?php endforeach;?>
        </select>
        <select class="form-control span2" id="class-select" onchange="changeClass()">
            <option value="0">全部</option>
        </select>
<!--        <select class="form-control span2" id="state-select" onchange="changeState()">-->
<!--            <option value="0">全部</option>-->
<!--            <option value="1">正常</option>-->
<!--            <option value="8">解约</option>-->
<!--            <option value="9">禁用</option>-->
<!--        </select>-->

        <div class="input-group span3">
            <input type="text" class="form-control span9" id="searchText">
             <span class="input-group-btn">
             <button class="btn btn-default" type="button" onclick="searchTextChange()">查找</button>
             </span>
        </div><!-- /input-group -->
        <div class="span1 pull-right" id="loading" style="display: none;">
            <img src="<?php echo $this->basePath()?>/images/loading.gif" style="width: 34px;"/>
        </div>
<!--        <button class="btn btn-default span2" onclick="test()" style="display: block">TEST</button>-->
        <!--        <input class="span3" type="file" accept="image/*" id="file" onchange="fileChanged(this)"/>-->
    </div>
    <!--    <input type="search" class="form-control"/>-->
    <div style="padding-top: 5px;">
        <table class="table table-bordered table-hover">
            <thead style="background-color:#428bca;color: white;">
            <tr>
                <td style="width: 30px"><input id="check-all" type="checkbox" onclick="checkAllBoxes()"/></td>
                <td>商品名称</td>
<!--                <td>价格</td>-->
                <td>所属分类</td>
                <td>所属卖家</td>
                <td>状态</td>
                <td width="130px">操作</td>
            </tr>
            </thead>
            <tbody style="background-color: white" id="goodsTable">
            <?php foreach ($goodsTable as $goods): ?>
                <tr id="tr-<?php echo $goods->getID()?>">
                    <td><input id="check-<?php echo $goods->getID();?>" type="checkbox"/></td>
                    <td><?php echo $goods->getName(); ?></td>
<!--                    <td>--><?php //echo $goods->getPrice(); ?><!--</td>-->
                    <td><?php echo $goods->getMainClassName()."-".$goods->getClassName(); ?></td>
                    <td><?php echo $goods->getSellerName(); ?></td>
                    <td>
                        <?php
                        $state = $goods->getState();
                        switch($state){
                            case 1:echo "在售";break;
                            case 2:echo "售罄";break;
                            default: echo "未知";break;
                        }
                        ?>
                    </td>
                    <td>
                        <a href="#" onclick="viewGoods(<?php echo $goods->getID(); ?>)">查看</a>
                        <a href="#" onclick="editGoodsOpen(<?php echo $goods->getID(); ?>)">编辑</a>
                        <a href="#" onclick="editStandardOpen(<?php echo $goods->getID();?>)">规格</a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <!--        分页-->
        <ul class="pager">
            <li><a href="#" onclick="prevPage()">上一页</a></li>
            <li class="disabled"><span>第<span id="curPage">1</span>页/共<span id="allPages"><?php echo ceil($count/10)?></span>页</span></li>
            <li><a href="#" onclick="nextPage()">下一页</a></li>
        </ul>

    </div>


</div>


<!--    添加商品-->
<div class="modal fade" id="addGoods" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 450px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title">添加商品</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="reg-sellerId" class="col-sm-3 control-label">商家</label>
                        <div class="col-sm-8">
                            <select class="form-control" id="reg-sellerId">
                                <?php foreach($sellerTable as $seller):?>
                                <option value="<?php echo $seller->getID()?>"><?php echo $seller->getName()?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="reg-mainClassId" class="col-sm-3 control-label">主分类</label>
                        <div class="col-sm-8">
                            <select class="form-control" id="reg-mainClassId" onchange="changeMainClassInAdd()">
                                <option value="0">请选择</option>
                                <?php foreach ($mainClassTable as $mainClass): ?>
                                    <option value="<?php echo $mainClass->getID()?>"><?php echo $mainClass->getName()?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="reg-classId" class="col-sm-3 control-label">分类</label>
                        <div class="col-sm-8">
                            <select class="form-control" id="reg-classId">

                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="reg-name" class="col-sm-3 control-label">商品名称</label>
                        <div class="col-sm-8">
                            <input type="email" class="form-control" id="reg-name" placeholder="请输入商品名称">
                        </div>
                    </div>
                    <div class="form-group" id="reg-showImg" style="display: none;">
                        <label for="reg-image" class="col-sm-3 control-label"></label>
                        <div class="col-sm-8">
                            <img id="reg-img" src="#" style="width: 200px; max-height: 150px"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="reg-image" class="col-sm-3 control-label">商品图片</label>
                        <div class="col-sm-8">
                            <input type="file" accept="image/*" class="form-control" id="reg-image"
                                   onchange="imageChanged(this,$('#reg-img'))">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="reg-price" class="col-sm-3 control-label">商品价格</label>
                        <div class="col-sm-8">
                            <div class="input-group">
                                <input type="email" class="form-control" id="reg-price" placeholder="请输入商品价格">
                                <div class="input-group-addon">每</div>
<!--                                <select id="reg-unit" class="form-control" style="width: 100px;">-->
<!--                                    <option>个</option>-->
<!--                                    <option>份</option>-->
<!--                                    <option>袋</option>-->
<!--                                    <option>包</option>-->
<!--                                    <option>盒</option>-->
<!--                                    <option>罐</option>-->
<!--                                    <option>瓶</option>-->
<!--                                    <option>支</option>-->
<!--                                    <option>斤</option>-->
<!--                                </select>-->
                                <input id="reg-unit" class="form-control" style="width: 100px;"/>
                            </div>

                        </div>
                    </div>
<!--                    <div class="form-group">-->
<!--                        <label for="reg-standard" class="col-sm-3 control-label">商品规格</label>-->
<!--                        <div class="col-sm-8">-->
<!--                            <input type="text" class="form-control" id="reg-standard" placeholder="请输入商品规格 如：500ml">-->
<!--                        </div>-->
<!--                    </div>-->
                </form>
            </div>
            <div class="modal-footer">
                <div style="float:left;margin-left: 80px; width: 200px;"><div id="reg-message" style="color: red;"></div></div>
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" onclick="addGoods()">确定</button>
            </div>
        </div>
    </div>
</div>

<!--    编辑商品-->
<div class="modal fade" id="editGoods" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 450px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title">编辑商品</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form">
                    <input type="text" class="form-control" id="edit-id" style="display: none"/>
                    <div class="form-group">
                        <label for="edit-seller" class="col-sm-3 control-label">商家</label>
                        <div class="col-sm-8">
                            <input id="edit-sellerId" style="display: none;"/>
                            <input id="edit-seller" class="form-control" readonly/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit-mainClassId" class="col-sm-3 control-label">主分类</label>
                        <div class="col-sm-8">
                            <select class="form-control" id="edit-mainClassId" onchange="changeMainClassInEdit()">
                                <?php foreach ($mainClassTable as $mainClass): ?>
                                    <option value="<?php echo $mainClass->getID()?>"><?php echo $mainClass->getName()?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit-classId" class="col-sm-3 control-label">分类</label>
                        <div class="col-sm-8">
                            <select class="form-control" id="edit-classId">

                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit-name" class="col-sm-3 control-label">商品名称</label>
                        <div class="col-sm-8">
                            <input type="email" class="form-control" id="edit-name"/>
                        </div>
                    </div>
                    <div class="form-group" id="edit-showImg">
                        <div class="col-sm-3"></div>
                        <div class="col-sm-8">
                            <img id="edit-img" style="width: 200px; max-height: 150px;"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit-image" class="col-sm-3 control-label">商家图片</label>
                        <div class="col-sm-8">
                            <input type="file" accept="image/*" class="form-control" id="edit-image"
                                   onchange="imageChanged(this, $('#edit-img'))">
                        </div>
                    </div>
<!--                    <div class="form-group">-->
<!--                        <label for="edit-price" class="col-sm-3 control-label">商品价格</label>-->
<!--                        <div class="col-sm-8">-->
<!--                            <div class="input-group">-->
<!--                                <input type="email" class="form-control" id="edit-price"/>-->
<!--                                <div class="input-group-addon">每</div>-->
<!--                                <select id="edit-unit" class="form-control" style="width: 100px;">-->
<!--                                    <option>个</option>-->
<!--                                    <option>份</option>-->
<!--                                </select>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
                    <div class="form-group">
                        <label for="edit-price" class="col-sm-3 control-label">商品单位</label>
                        <div class="col-sm-8">
<!--                                <select id="edit-unit" class="form-control" style="width: 100px;">-->
<!--                                    <option>个</option>-->
<!--                                    <option>份</option>-->
<!--                                    <option>袋</option>-->
<!--                                    <option>包</option>-->
<!--                                    <option>盒</option>-->
<!--                                    <option>罐</option>-->
<!--                                    <option>瓶</option>-->
<!--                                    <option>支</option>-->
<!--                                    <option>斤</option>-->
<!--                                </select>-->
                            <input id="edit-unit" class="form-control" style="width: 100px;"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit-state" class="col-sm-3 control-label">状态</label>
                        <div class="col-sm-8">
                            <select id="edit-state" class="form-control">
                                <option value="1">在售</option>
                                <option value="2">售罄</option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <div style="float:left;margin-left: 80px; width: 200px;"><div id="edit-message" style="color: red;"></div></div>
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" onclick="editGoods()">确定</button>
            </div>
        </div>
    </div>
</div>


<!--    查看商品-->
<div class="modal fade" id="viewGoods" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 450px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title">查看商品</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <img id="view-image" style="width: 200px; max-height: 150px;" class="center-block"/>
                    </div>
                    <div class="form-group">
                        <label for="view-seller" class="col-sm-4 control-label">商家名称</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="view-seller"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="view-mainClass" class="col-sm-4 control-label">主分类</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="view-mainClass"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="view-class" class="col-sm-4 control-label">子分类</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="view-class"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="view-name" class="col-sm-4 control-label">商品名称</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="view-name"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="view-price" class="col-sm-4 control-label">价格</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="view-price"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="view-state" class="col-sm-4 control-label">状态</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="view-state"></p>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
            </div>
        </div>
    </div>
</div>

<!--    编辑商品规格 -->
<div class="modal fade" id="editStandard" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 450px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title">编辑商品规格</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form">
                    <input type="text" class="form-control" id="edit-standard-id" style="display: none"/>
                    <div class="form-group">
                        <label for="view-name" class="col-sm-4 control-label">商品名称</label>
                        <div class="col-sm-7">
                            <p class="form-control-static" id="edit-standard-name"></p>
                        </div>
                    </div>
                    <hr/>
                    <div class="form-group">
                        <div class="col-sm-4" style="text-align: center;font-weight: bold;">
                            规格
                        </div>
                        <div class="col-sm-4" style="text-align: center;font-weight: bold;">
                            价格
                        </div>
                        <div class="col-sm-3" style="text-align: center;font-weight: bold;">
                            状态
                        </div>
                    </div>

<!--                    <div class="form-group standard-group">-->
<!--                        <div class="col-sm-4">-->
<!--                            <input type="email" class="form-control standard-standard"/>-->
<!--                        </div>-->
<!--                        <div class="col-sm-4">-->
<!--                            <input type="email" class="form-control standard-price"/>-->
<!--                        </div>-->
<!--                        <div class="col-sm-3">-->
<!--                            <select class="form-control standard-state">-->
<!--                                <option value="1">在售</option>-->
<!--                                <option value="2">售罄</option>-->
<!--                            </select>-->
<!--                        </div>-->
<!--                        <div class="col-sm-1">-->
<!--                            <button type="button" class="close" onclick="removeStandard($(this))"><span aria-hidden="true">&times;</span></button>-->
<!--                        </div>-->
<!--                    </div>-->

                    <div class="form-group" id="standard-add">
                        <div class="col-sm-4">
                            <a href="###" onclick="addBlankStandard()">添加新规格</a>
                        </div>
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <div style="float:left;margin-left: 80px; width: 200px;"><div id="edit-standard-message" style="color: red;"></div></div>
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" onclick="editStandardSubmit()">确定</button>
            </div>
        </div>
    </div>
</div>

<!--<button class="btn btn-info" onclick="editStandardOpen(220062)">test</button>-->