<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Home\Module'                        => __DIR__ . '/Module.php',
    'Home\Controller\HomeController' => __DIR__ . '/src/Home/Controller/HomeController.php',
    'HomeTest\Framework\TestCase'        => __DIR__ . '/tests/Home/Framework/TestCase.php',
    'HomeTest\SampleTest'                => __DIR__ . '/tests/Home/SampleTest.php',
);
