
<div>

        <img class="home-logo" src="http://static.kuaidishu.com/images/logo.jpg" />

</div>

<form role="form" onsubmit="return false">
    <div class="form-group">
        <label for="exampleInputEmail1">快递鼠帐号</label>
        <input type="text" class="form-control" id="username" placeholder="请输入快递鼠帐号">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">密码</label>
        <input type="password" class="form-control" id="password" placeholder="请输入密码">
    </div>
    <br/>
    <button type="submit" class="btn btn-default form-control" onclick="confirmBinding()">确认绑定</button>
</form>