

<div  class="messagebox">
    <div class="mainMsg">
    <?php
    echo $this->message;
    ?>
    </div>
</div>

<style>
    .messagebox{
        margin: 0 auto;
        float: none;
        padding: 10px 0;
        position: relative;
        box-shadow: 0 0 10px #d7d7d7;
        background-color: #ffffff;
        border: 1px solid #d7d7d7;
        height: 200px;
    }
    .mainMsg{
        margin: 0 auto;
        padding: 10px;
        font-size: 28px;
    }
</style>