<nav class="navbar navbar-default navbar-mobile-home" >
    <div class="container">
        <div class="row-fluid navbar-mobile-home content">
            <div class="pull-left">
                <span style="color: white !important" class="glyphicon glyphicon-map-marker"></span>
                广州大学
            </div>
            <div class="pull-right">
                <span style="color: white !important" class="glyphicon glyphicon-search"></span>
            </div>
        </div>
    </div>
</nav>
<div class="btn-group btn-group-justified" style="width: 100%">
    <div class="btn-group" style="width: 33.3%">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" style="width: 100%">
            全部分类
<!--            <span class="caret"></span>-->
        </button>
        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">全部分类</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">超市</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">宵夜小吃</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">中餐快餐</a></li>
        </ul>
    </div>
    <div class="btn-group" style="width: 33.4%">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" style="width: 100%">
            默认排序
<!--            <span class="caret"></span>-->
        </button>
        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu2">
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">默认排序</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">销量最多</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">评价最多</a></li>
        </ul>
    </div>
    <div class="btn-group" style="width: 33.3%">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu3" data-toggle="dropdown" style="width: 100%">
            商家过滤
<!--            <span class="caret"></span>-->
        </button>
        <ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="dropdownMenu3">
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">商家过滤</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">用低价卷</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">可开发票</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">超时赔付</a></li>
        </ul>
    </div>
</div>


<?php echo $sellerHtml?>



</div>